#include "map.h"
Ttree create_tree();
int is_empty(Ttree tree);
Tnode minimum(Tnode x);
Tnode maximum(Tnode x);
Tnode search(Ttree tree, int id_key);
Tnode successor(Tnode x);
Tnode predecessor(Tnode x);
void update_height(Tnode x);
void avl_rotate_left(Ttree tree, Tnode x);
void avl_rotate_right(Ttree tree, Tnode x);
int balance_factor(Tnode x);
long maxim(long a, long b);
void avl_fix_up(Ttree tree, Tnode y);
Tnode init_node(Ttree tree, Tuser key);
void insert_node(Ttree tree, Tuser key);
Tnode build_tree_pivot(Tnode lt, Tnode rt);
Tnode deepest_node(Tnode root);
void destroy_node(Ttree tree, Tnode node);
void delete_node(Ttree tree, Tuser key);
void destroy_tree(Ttree tree);
void destroy_tree_helper(Ttree tree, Tnode root);